### PR TITLE
defined new page container classes. applied to home and article pages

### PR DESCRIPTION
**Pull request by anandamaryon**
have not applied to all pages because there is still a lot of duplicate pages that refactoring to use the same components. (article pages, landing pages.)

home page will need the page container opening and closing to allow for the blockquote's white background to go full-width.

@anandamaryon yes only apply to one component. Maybe someone can look at article page refactor today.  If you let me know which if someone is free to pick up this afternoon
@anandamaryon at Niall is refactoring the generic pages now.

### CODE REVIEW

**Comment by kingdomlevel** [comment]
FYI the re-factoring work is issue #47 in this repo!

**Review by yemijaiyeola — APPROVED** [review]

**Comment by yemijaiyeola** [comment]
Screenshot 2021-04-28 at 14 04 25
Reviewed and approved

**Comment by yemijaiyeola** [comment]
As Niall is around he can provide the second review then you can merge.

**Comment by yemijaiyeola** [comment]
See screenshot make sure you are happy that's what I see.

**Comment by anandamaryon** [comment]
@yemijaiyeola @kingdomlevel 

I only applied to homepage and GenericContentPage so far. Can apply to other pages after refactor by @kingdomlevel

**Review by kingdomlevel — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
