### PR TITLE
focus state for case-study link styles fix

### PR DESCRIPTION
**Pull request by anandamaryon**
fixes issue number 5 on this sheet: https://docs.google.com/spreadsheets/d/1d6n4jL0ww5_hIw4UwKA-4yml0Ocs_wc-_HQPzr16t0o/edit#gid=2081076411

### CODE REVIEW

**Review by kingdomlevel — CHANGES_REQUESTED** [review]
Working for me on the case studies link on homepage... however...

I did notice another one on mobile, immediately after clicking on the 'open menu' button - the active + focus states will likely fail (see screenshot):
image

**Comment by anandamaryon** [comment]
Thanks @kingdomlevel I'll look at this now

**Comment by anandamaryon** [comment]
@kingdomlevel I believe I've fixed all of the states now

**Review by kingdomlevel — DISMISSED** [review]
Looks beautiful to me

**Comment by kingdomlevel** [comment]
FYI I wrongly committed against this branch so dismissed my own review - sorry! It still looks good to me

**Review by kingdomlevel — APPROVED** [review]

**Review by yemijaiyeola — APPROVED** [review]

**Pull request merged**
